# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "am.ik.buildpacks.jvmkill"
version = "0.1.0"
name = "JVMKill Agent Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.dependencies]]
id = "jvmkill"
name = "JVMKill Agent"
version = "1.16.0"
uri = "https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0_RELEASE.so"
sha256 = "a3092627b082cb3cdbbe4b255d35687126aa604e6b613dcda33be9f7e1277162"

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri = "https://github.com/cloudfoundry/jvmkill/blob/master/LICENSE"
